import request from '@/utils/request'

export function getList(params) {
  return request({
    url: '/table/list',
    method: 'get',
    params
  })
}
export const per = {
  'code': 200,
  'data': [
    {
      'id': 1,
      'pid': 0,
      'top': 1,
      'home': 1,
      'name': 'member',
      'title': '会员管理',
      'icon': 'wxgh icon-member-default',
      'path': 'index.php?c=home&a=first&do=member',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 2,
          'pid': 1,
          'top': 0,
          'home': 0,
          'name': 'member',
          'title': '会员管理',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 3,
              'pid': 2,
              'top': 0,
              'home': 0,
              'name': 'member_union',
              'title': '工会组织架构',
              'icon': 'wxgh icon-member-mechanism',
              'path': 'index.php?c=member&a=union',
              'thumb': 'null',
              'type': 1,
              'hide': 0,
              'children': [
                {
                  'id': 4,
                  'pid': 3,
                  'top': 0,
                  'home': 0,
                  'name': 'member_union_add',
                  'title': '添加子级机构',
                  'icon': '',
                  'path': 'index.php?c=member&a=union&do=add',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 5,
                  'pid': 3,
                  'top': 0,
                  'home': 0,
                  'name': 'member_union_edit',
                  'title': '编辑',
                  'icon': '',
                  'path': 'index.php?c=member&a=union&do=edit',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 6,
                  'pid': 3,
                  'top': 0,
                  'home': 0,
                  'name': 'member_union_delete',
                  'title': '删除',
                  'icon': '',
                  'path': 'index.php?c=member&a=union&do=delete',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                }
              ]
            },
            {
              'id': 7,
              'pid': 2,
              'top': 0,
              'home': 0,
              'name': 'member_centre',
              'title': '会员中心',
              'icon': 'wxgh icon-member-core',
              'path': 'index.php?c=member&a=centre',
              'thumb': 'null',
              'type': 1,
              'hide': 0,
              'children': [
                {
                  'id': 8,
                  'pid': 7,
                  'top': 0,
                  'home': 0,
                  'name': 'member_centre_add',
                  'title': '添加\/编辑会员',
                  'icon': '',
                  'path': 'index.php?c=member&a=centre&do=add',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 9,
                  'pid': 7,
                  'top': 0,
                  'home': 0,
                  'name': 'member_centre_import',
                  'title': '导入',
                  'icon': '',
                  'path': 'index.php?c=member&a=centre&do=import',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 10,
                  'pid': 7,
                  'top': 0,
                  'home': 0,
                  'name': 'member_centre_export',
                  'title': '导出',
                  'icon': '',
                  'path': 'index.php?c=member&a=centre&do=export',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 11,
                  'pid': 7,
                  'top': 0,
                  'home': 0,
                  'name': 'member_centre_delete',
                  'title': '删除',
                  'icon': '',
                  'path': 'index.php?c=member&a=centre&do=delete',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                }
              ]
            },
            {
              'id': 169,
              'pid': 2,
              'top': 0,
              'home': 0,
              'name': 'member_hard',
              'title': '困难职工管理',
              'icon': 'wxgh icon-member-difficulty',
              'path': 'index.php?c=member&a=hard',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 173,
              'pid': 2,
              'top': 0,
              'home': 0,
              'name': 'member_data',
              'title': '会员数据统计',
              'icon': 'wxgh icon-member-data',
              'path': 'index.php?c=member&a=data',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 12,
      'pid': 0,
      'top': 0,
      'home': 0,
      'name': 'account',
      'title': '公众号',
      'icon': 'wi wi-white-collar',
      'path': 'index.php?c=home&a=first&do=account',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 13,
          'pid': 12,
          'top': 0,
          'home': 0,
          'name': 'platform_plus',
          'title': '增强功能',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 14,
              'pid': 13,
              'top': 0,
              'home': 0,
              'name': 'platform_reply',
              'title': '自动回复',
              'icon': 'wi wi-reply',
              'path': 'index.php?c=platform&a=reply',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 15,
              'pid': 13,
              'top': 0,
              'home': 0,
              'name': 'platform_menu',
              'title': '自定义菜单',
              'icon': 'wi wi-custommenu',
              'path': 'index.php?c=platform&a=menu&do=post',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 16,
      'pid': 0,
      'top': 1,
      'home': 1,
      'name': 'system',
      'title': '公众号管理',
      'icon': 'wxgh icon-account-default',
      'path': 'index.php?c=home&a=first&do=system',
      'thumb': 'null',
      'type': 1,
      'hide': 0
    },
    {
      'id': 40,
      'pid': 0,
      'top': 1,
      'home': 1,
      'name': 'news',
      'title': '图文管理',
      'icon': 'wxgh icon-news-default',
      'path': 'index.php?c=home&a=first&do=news',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 41,
          'pid': 40,
          'top': 0,
          'home': 0,
          'name': 'news',
          'title': '公众号推文',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 42,
              'pid': 41,
              'top': 0,
              'home': 0,
              'name': 'news_templet',
              'title': '图文模板',
              'icon': 'wxgh icon-news-template',
              'path': 'index.php?c=news&a=templet',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 43,
              'pid': 41,
              'top': 0,
              'home': 0,
              'name': 'news_my',
              'title': '我创建的图文',
              'icon': 'wxgh icon-news-my',
              'path': 'index.php?c=news&a=my',
              'thumb': 'null',
              'type': 1,
              'hide': 0,
              'children': [
                {
                  'id': 44,
                  'pid': 43,
                  'top': 0,
                  'home': 0,
                  'name': 'news_fabu',
                  'title': '发布图文',
                  'icon': '',
                  'path': 'index.php?c=news&a=fabu',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 45,
                  'pid': 43,
                  'top': 0,
                  'home': 0,
                  'name': 'news_my_del',
                  'title': '删除图文',
                  'icon': '',
                  'path': 'index.php?c=news&a=my&do=del',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                }
              ]
            },
            {
              'id': 158,
              'pid': 41,
              'top': 0,
              'home': 0,
              'name': 'news_material',
              'title': '企业素材库',
              'icon': 'wxgh icon-news-company',
              'path': 'index.php?c=news&a=material',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 162,
              'pid': 41,
              'top': 0,
              'home': 0,
              'name': 'news_published',
              'title': '已发布图文',
              'icon': 'wxgh icon-news-published',
              'path': 'index.php?c=news&a=published',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 174,
              'pid': 41,
              'top': 0,
              'home': 0,
              'name': 'news_data',
              'title': '数据统计',
              'icon': 'wxgh icon-other-data',
              'path': 'index.php?c=news&a=data',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 53,
      'pid': 0,
      'top': 1,
      'home': 1,
      'name': 'activity',
      'title': '活动管理',
      'icon': 'wxgh icon-activity-default',
      'path': 'index.php?c=home&a=first&do=activity',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 54,
          'pid': 53,
          'top': 0,
          'home': 0,
          'name': 'activity',
          'title': '活动管理',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 56,
              'pid': 54,
              'top': 0,
              'home': 0,
              'name': 'activity_templet',
              'title': '活动模板',
              'icon': 'wxgh icon-activity-templet',
              'path': 'index.php?c=activity&a=templet',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 57,
              'pid': 54,
              'top': 0,
              'home': 0,
              'name': 'activity_noreleased',
              'title': '我创建的活动',
              'icon': 'wxgh icon-activity-my',
              'path': 'index.php?c=activity&a=noreleased',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 150,
              'pid': 54,
              'top': 0,
              'home': 0,
              'name': 'activity_published',
              'title': '已发布活动',
              'icon': 'wxgh icon-activity-published',
              'path': 'index.php?c=activity&a=published',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 178,
              'pid': 54,
              'top': 0,
              'home': 0,
              'name': 'activity_data',
              'title': '数据统计',
              'icon': 'wxgh icon-activity-data',
              'path': 'index.php?c=activity&a=data',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 61,
      'pid': 0,
      'top': 1,
      'home': 1,
      'name': 'survey',
      'title': '问卷调查',
      'icon': 'wxgh icon-survey-default',
      'path': 'index.php?c=home&a=first&do=survey',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 62,
          'pid': 61,
          'top': 0,
          'home': 0,
          'name': 'survey',
          'title': '问卷调查',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 63,
              'pid': 62,
              'top': 0,
              'home': 0,
              'name': 'survey_templet',
              'title': '问卷模板',
              'icon': 'wxgh icon-survey-templet',
              'path': 'index.php?c=survey&a=templet',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 64,
              'pid': 62,
              'top': 0,
              'home': 0,
              'name': 'survey_add',
              'title': '创建问卷',
              'icon': 'wxgh icon-survey-add',
              'path': 'index.php?c=survey&a=add',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 65,
              'pid': 62,
              'top': 0,
              'home': 0,
              'name': 'survey_noreleased',
              'title': '我创建的问卷',
              'icon': 'wxgh icon-survey-my',
              'path': 'index.php?c=survey&a=noreleased',
              'thumb': 'null',
              'type': 1,
              'hide': 0,
              'children': [
                {
                  'id': 60,
                  'pid': 65,
                  'top': 0,
                  'home': 0,
                  'name': 'survey_details',
                  'title': '问卷详情',
                  'icon': 'wi wi-site-setting',
                  'path': 'index.php?c=survey&a=details',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                }
              ]
            },
            {
              'id': 152,
              'pid': 62,
              'top': 0,
              'home': 0,
              'name': 'survey_published',
              'title': '已发布问卷',
              'icon': 'wxgh icon-survey-published',
              'path': 'index.php?c=survey&a=published',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 176,
              'pid': 62,
              'top': 0,
              'home': 0,
              'name': 'survey_data',
              'title': '数据统计',
              'icon': 'wxgh icon-survey-data',
              'path': 'index.php?c=survey&a=data',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 66,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'canteen',
      'title': '我的食堂',
      'icon': 'wxgh icon-canteen-default',
      'path': 'index.php?c=home&a=first&do=canteen',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 244,
          'pid': 66,
          'top': 0,
          'home': 0,
          'name': 'canteenManage',
          'title': '食堂管理',
          'icon': 'form',
          'path': '\/a\/#\/Canteen\/canteenManage',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 245,
          'pid': 66,
          'top': 0,
          'home': 0,
          'name': 'dishesAllocation',
          'title': '菜肴配置',
          'icon': 'form',
          'path': '\/a\/#\/Canteen\/dishesAllocation',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 246,
          'pid': 66,
          'top': 0,
          'home': 0,
          'name': 'dishesManage',
          'title': '菜谱管理',
          'icon': 'form',
          'path': '\/a\/#\/Canteen\/dishesManage',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 247,
          'pid': 66,
          'top': 0,
          'home': 0,
          'name': 'dishesComment',
          'title': '菜谱评价',
          'icon': 'form',
          'path': '\/a\/#\/Canteen\/dishesComment',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 248,
          'pid': 66,
          'top': 0,
          'home': 0,
          'name': 'detailReser',
          'title': '预约就餐明细',
          'icon': 'form',
          'path': '\/a\/#\/Canteen\/detailReser',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 249,
          'pid': 66,
          'top': 0,
          'home': 0,
          'name': 'reserStatic',
          'title': '预约统计',
          'icon': 'form',
          'path': '\/a\/#\/Canteen\/reserStatic',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 250,
          'pid': 66,
          'top': 0,
          'home': 0,
          'name': 'baseConfig',
          'title': '基础配置',
          'icon': 'form',
          'path': '\/a\/#\/Canteen\/baseConfig',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 251,
          'pid': 66,
          'top': 0,
          'home': 0,
          'name': 'eatNextWeek',
          'title': '查看投票',
          'icon': 'form',
          'path': '\/a\/#\/Canteen\/eatNextWeek',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 252,
          'pid': 66,
          'top': 0,
          'home': 0,
          'name': 'lookContain',
          'title': '查看内容',
          'icon': 'form',
          'path': '\/a\/#\/Canteen\/lookContain',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        }
      ]
    },
    {
      'id': 90,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'photowall',
      'title': '照片墙',
      'icon': 'wxgh icon-photo-default',
      'path': 'index.php?c=home&a=first&do=photowall',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 91,
          'pid': 90,
          'top': 0,
          'home': 0,
          'name': 'photowall',
          'title': '照片墙',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 92,
              'pid': 91,
              'top': 0,
              'home': 0,
              'name': 'photowall_list',
              'title': '照片墙图片',
              'icon': 'wxgh icon-photo-info',
              'path': 'index.php?c=photowall&a=list',
              'thumb': 'null',
              'type': 1,
              'hide': 0,
              'children': [
                {
                  'id': 93,
                  'pid': 92,
                  'top': 0,
                  'home': 0,
                  'name': 'photowall_list_details',
                  'title': '查看详情',
                  'icon': '',
                  'path': 'index.php?c=photowall&a=list&do=details',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 94,
                  'pid': 92,
                  'top': 0,
                  'home': 0,
                  'name': 'photowall_list_delete',
                  'title': '删除照片墙',
                  'icon': '',
                  'path': 'index.php?c=photowall&a=list&do=delete',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                }
              ]
            },
            {
              'id': 172,
              'pid': 91,
              'top': 0,
              'home': 0,
              'name': 'photowall_data',
              'title': '数据统计',
              'icon': 'wxgh icon-photo-data',
              'path': 'index.php?c=photowall&a=data',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 95,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'manager',
      'title': '总经理信箱',
      'icon': 'wxgh icon-manager-default',
      'path': 'index.php?c=home&a=first&do=manager',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 96,
          'pid': 95,
          'top': 0,
          'home': 0,
          'name': 'manager',
          'title': '总经理信箱',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 97,
              'pid': 96,
              'top': 0,
              'home': 0,
              'name': 'manager_unhandle',
              'title': '待处理',
              'icon': 'wxgh icon-manager-unhandle',
              'path': 'index.php?c=manager&a=unhandle',
              'thumb': 'null',
              'type': 1,
              'hide': 0,
              'children': [
                {
                  'id': 98,
                  'pid': 97,
                  'top': 0,
                  'home': 0,
                  'name': 'manager_unhandle_info',
                  'title': '处理信件',
                  'icon': '',
                  'path': 'index.php?c=manager&a=unhandle&do=info',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 99,
                  'pid': 97,
                  'top': 0,
                  'home': 0,
                  'name': 'manager_unhandle_info1',
                  'title': '查看信件',
                  'icon': '',
                  'path': 'index.php?c=manager&a=unhandle&do=info1',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                }
              ]
            },
            {
              'id': 100,
              'pid': 96,
              'top': 0,
              'home': 0,
              'name': 'manager_handle',
              'title': '已处理',
              'icon': 'wxgh icon-manager-handle',
              'path': 'index.php?c=manager&a=handle',
              'thumb': 'null',
              'type': 1,
              'hide': 0,
              'children': [
                {
                  'id': 101,
                  'pid': 100,
                  'top': 0,
                  'home': 0,
                  'name': 'manager_handle_info',
                  'title': '处理信件',
                  'icon': '',
                  'path': 'index.php?c=manager&a=handle&do=info',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 102,
                  'pid': 100,
                  'top': 0,
                  'home': 0,
                  'name': 'manager_handle_info1',
                  'title': '查看信件',
                  'icon': '',
                  'path': 'index.php?c=manager&a=handle&do=info1',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                }
              ]
            },
            {
              'id': 103,
              'pid': 96,
              'top': 0,
              'home': 0,
              'name': 'manager_list',
              'title': '总经理列表',
              'icon': 'wxgh icon-manager-list',
              'path': 'index.php?c=manager&a=manager_list',
              'thumb': 'null',
              'type': 1,
              'hide': 0,
              'children': [
                {
                  'id': 104,
                  'pid': 103,
                  'top': 0,
                  'home': 0,
                  'name': 'manager_list_add',
                  'title': '添加编辑总经理',
                  'icon': '',
                  'path': 'index.php?c=manager&a=manager_list&do=add',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 105,
                  'pid': 103,
                  'top': 0,
                  'home': 0,
                  'name': 'manager_list_delete',
                  'title': '禁用总经理',
                  'icon': '',
                  'path': 'index.php?c=manager&a=manager_list&do=delete',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 106,
                  'pid': 103,
                  'top': 0,
                  'home': 0,
                  'name': 'manager_list_up',
                  'title': '启用总经理',
                  'icon': '',
                  'path': 'index.php?c=manager&a=manager_list&do=up',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                },
                {
                  'id': 107,
                  'pid': 103,
                  'top': 0,
                  'home': 0,
                  'name': 'manager_list_info',
                  'title': '查看详情',
                  'icon': '',
                  'path': 'index.php?c=manager&a=manager_list&do=info',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                }
              ]
            }
          ]
        }
      ]
    },
    {
      'id': 108,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'hotfocus',
      'title': '热点关注',
      'icon': 'wxgh icon-hotfocus-default',
      'path': 'index.php?c=home&a=first&do=hotfocus',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 109,
          'pid': 108,
          'top': 0,
          'home': 0,
          'name': 'hotfocus',
          'title': '热点关注',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 110,
              'pid': 109,
              'top': 0,
              'home': 0,
              'name': 'hotfocus_released',
              'title': '我创建的热点关注',
              'icon': 'wxgh icon-hotfocus-my',
              'path': 'index.php?c=hotfocus&a=released',
              'thumb': 'null',
              'type': 1,
              'hide': 0,
              'children': [
                {
                  'id': 113,
                  'pid': 110,
                  'top': 0,
                  'home': 0,
                  'name': 'hotfocus_fabu',
                  'title': '发布',
                  'icon': '',
                  'path': 'index.php?c=hotfocus&a=fabu',
                  'thumb': 'null',
                  'type': 1,
                  'hide': 0
                }
              ]
            }
          ]
        }
      ]
    },
    {
      'id': 116,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'banner',
      'title': '轮播图管理',
      'icon': 'wxgh icon-banner-default',
      'path': 'index.php?c=home&a=first&do=banner',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 117,
          'pid': 116,
          'top': 0,
          'home': 0,
          'name': 'banner',
          'title': '轮播图管理',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 118,
              'pid': 117,
              'top': 0,
              'home': 0,
              'name': 'banner_list',
              'title': '轮播图列表',
              'icon': 'wxgh icon-banner-list',
              'path': 'index.php?c=banner&a=banner_list',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 161,
              'pid': 117,
              'top': 0,
              'home': 0,
              'name': 'my_banner',
              'title': '我创建的',
              'icon': 'wxgh icon-banner-my',
              'path': 'index.php?c=banner&a=my_list',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 119,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'welfare',
      'title': '抢福利管理',
      'icon': 'wxgh icon-welfare-default',
      'path': 'index.php?c=home&a=first&do=welfare',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 120,
          'pid': 119,
          'top': 0,
          'home': 0,
          'name': 'welfare',
          'title': '抢福利管理',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 121,
              'pid': 120,
              'top': 0,
              'home': 0,
              'name': 'welfare_business',
              'title': '福利管理',
              'icon': 'wxgh icon-welfare-manage',
              'path': 'index.php?c=welfare&a=business',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 123,
              'pid': 120,
              'top': 0,
              'home': 0,
              'name': 'welfare_depot',
              'title': '已发布福利',
              'icon': 'wxgh icon-welfare-published',
              'path': 'index.php?c=welfare&a=depot',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 124,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'freeride',
      'title': '顺风车管理',
      'icon': 'wxgh icon-freeride-default',
      'path': 'index.php?c=home&a=first&do=freeride',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 125,
          'pid': 124,
          'top': 0,
          'home': 0,
          'name': 'freeride',
          'title': '顺风车管理',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 126,
              'pid': 125,
              'top': 0,
              'home': 0,
              'name': 'freeride_commonweal',
              'title': '公益值排行',
              'icon': 'wxgh icon-freeride-commonweal',
              'path': 'index.php?c=freeride&a=commonweal',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 127,
              'pid': 125,
              'top': 0,
              'home': 0,
              'name': 'freeride_opinion',
              'title': '意见反馈',
              'icon': 'wxgh icon-freeride-opinion',
              'path': 'index.php?c=freeride&a=opinion',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 128,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'club',
      'title': '我的俱乐部',
      'icon': 'wxgh icon-club-default',
      'path': 'index.php?c=home&a=first&do=club',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 129,
          'pid': 128,
          'top': 0,
          'home': 0,
          'name': 'club',
          'title': '我的俱乐部',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 130,
              'pid': 129,
              'top': 0,
              'home': 0,
              'name': 'club_pending',
              'title': '俱乐部审核',
              'icon': 'wxgh icon-club-examine',
              'path': 'index.php?c=club&a=club_pending',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 132,
              'pid': 129,
              'top': 0,
              'home': 0,
              'name': 'club_funds_pending',
              'title': '经费审核',
              'icon': 'wxgh icon-club-funds-examine',
              'path': 'index.php?c=club&a=funds_pending',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 134,
              'pid': 129,
              'top': 0,
              'home': 0,
              'name': 'club_notice',
              'title': '俱乐部创建须知',
              'icon': 'wxgh icon-club-createnotes',
              'path': 'index.php?c=club&a=notice',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 175,
              'pid': 129,
              'top': 0,
              'home': 0,
              'name': 'club_data',
              'title': '数据统计',
              'icon': 'wxgh icon-club-data',
              'path': 'index.php?c=club&a=data',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 135,
      'pid': 0,
      'top': 0,
      'home': 0,
      'name': 'walk',
      'title': '健步PK赛',
      'icon': 'fa fa-glass',
      'path': 'index.php?c=home&a=first&do=walk',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 136,
          'pid': 135,
          'top': 0,
          'home': 0,
          'name': 'walk',
          'title': '健步PK赛',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 137,
              'pid': 136,
              'top': 0,
              'home': 0,
              'name': 'walk_situation',
              'title': '参赛情况',
              'icon': 'wxgh icon-walk-situation',
              'path': 'index.php?c=walk&a=situation',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 138,
              'pid': 136,
              'top': 0,
              'home': 0,
              'name': 'walk_irank',
              'title': '个人排名',
              'icon': 'wxgh icon-walk-irank',
              'path': 'index.php?c=walk&a=irank',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 139,
              'pid': 136,
              'top': 0,
              'home': 0,
              'name': 'walk_urank',
              'title': '工会排名',
              'icon': 'wxgh icon-walk-urank',
              'path': 'index.php?c=walk&a=urank',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 177,
              'pid': 136,
              'top': 0,
              'home': 0,
              'name': 'walk_setting',
              'title': '健步设置',
              'icon': 'wxgh icon-walk-set',
              'path': 'index.php?c=walk&a=setting',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 141,
      'pid': 0,
      'top': 0,
      'home': 0,
      'name': 'birth',
      'title': '生日趴管理',
      'icon': 'fa fa-gittip',
      'path': '',
      'thumb': 'null',
      'type': 1,
      'hide': 0
    },
    {
      'id': 142,
      'pid': 0,
      'top': 0,
      'home': 0,
      'name': 'whisper',
      'title': '悄悄话管理',
      'icon': 'fa fa-comments',
      'path': '',
      'thumb': 'null',
      'type': 1,
      'hide': 0
    },
    {
      'id': 143,
      'pid': 0,
      'top': 0,
      'home': 0,
      'name': 'video',
      'title': '健身房管理',
      'icon': 'fa fa-deviantart',
      'path': '',
      'thumb': 'null',
      'type': 1,
      'hide': 0
    },
    {
      'id': 153,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'care',
      'title': '关爱直通车',
      'icon': 'wxgh icon-care-default',
      'path': 'index.php?c=home&a=first&do=care',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 154,
          'pid': 153,
          'top': 0,
          'home': 0,
          'name': 'care',
          'title': '\t\r\n关爱直通车',
          'icon': ' ',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 155,
              'pid': 154,
              'top': 0,
              'home': 0,
              'name': 'care_type',
              'title': '帮扶类型',
              'icon': 'wxgh icon-care-helptype',
              'path': 'index.php?c=care&a=type_list',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 156,
              'pid': 154,
              'top': 0,
              'home': 0,
              'name': 'care_history',
              'title': '帮扶记录',
              'icon': 'wxgh icon-care-helprecord',
              'path': '\t\r\nindex.php?c=care&a=history',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 157,
              'pid': 154,
              'top': 0,
              'home': 0,
              'name': 'care_people',
              'title': '设置工会干事',
              'icon': 'wxgh icon-care-director',
              'path': 'index.php?c=care&a=worker',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 160,
              'pid': 154,
              'top': 0,
              'home': 0,
              'name': 'care_data',
              'title': '数据统计',
              'icon': 'wxgh icon-care-data',
              'path': 'index.php?c=care&a=data',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 164,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'integral',
      'title': '积分管理',
      'icon': 'wxgh icon-integral-default',
      'path': 'index.php?c=home&a=first&do=integral',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 165,
          'pid': 164,
          'top': 0,
          'home': 0,
          'name': 'integral',
          'title': '积分管理',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 166,
              'pid': 165,
              'top': 0,
              'home': 0,
              'name': 'integral_setting',
              'title': '积分设置',
              'icon': 'wxgh icon-integral-set',
              'path': 'index.php?c=integral&a=setting',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 167,
              'pid': 165,
              'top': 0,
              'home': 0,
              'name': 'integral_rule',
              'title': '积分规则说明',
              'icon': 'wxgh icon-integral-rule',
              'path': 'index.php?c=integral&a=rule',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 168,
              'pid': 165,
              'top': 0,
              'home': 0,
              'name': 'integral_member',
              'title': '会员积分统计',
              'icon': 'wxgh icon-integral-member',
              'path': 'index.php?c=integral&a=member',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 170,
              'pid': 165,
              'top': 0,
              'home': 0,
              'name': 'integral_statistics',
              'title': '数据统计',
              'icon': 'wxgh icon-integral-data',
              'path': 'index.php?c=integral&a=statistics',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 179,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'pat',
      'title': '隐患随手拍',
      'icon': 'wxgh icon-pat-default',
      'path': 'index.php?c=home&a=first&do=pat',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 180,
          'pid': 179,
          'top': 0,
          'home': 0,
          'name': 'pat',
          'title': '隐患随手拍',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 181,
              'pid': 180,
              'top': 0,
              'home': 0,
              'name': 'pat_list',
              'title': '隐患信息',
              'icon': 'wxgh icon-pat-info',
              'path': 'index.php?c=pat&a=list',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 182,
              'pid': 180,
              'top': 0,
              'home': 0,
              'name': 'pat_classify',
              'title': '隐患类别',
              'icon': 'wxgh icon-pat-category',
              'path': 'index.php?c=pat&a=classify',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 183,
              'pid': 180,
              'top': 0,
              'home': 0,
              'name': 'pat_data',
              'title': '数据统计',
              'icon': 'wxgh icon-pat-data',
              'path': 'index.php?c=pat&a=data',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 185,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'mall',
      'title': '福利积分',
      'icon': '',
      'path': 'index.php?c=home&a=first&do=mall',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 186,
          'pid': 185,
          'top': 0,
          'home': 0,
          'name': 'mall',
          'title': '福利积分',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 187,
              'pid': 186,
              'top': 0,
              'home': 0,
              'name': 'mall_setting',
              'title': '福利积分配置',
              'icon': 'wxgh icon-welfare-manage',
              'path': 'index.php?c=mall&a=setting',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 191,
              'pid': 186,
              'top': 0,
              'home': 0,
              'name': 'mall_arrival_record',
              'title': '积分到账记录',
              'icon': 'wxgh icon-canteen-result',
              'path': 'index.php?c=mall&a=arrival_record',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 196,
      'pid': 0,
      'top': 0,
      'home': 0,
      'name': 'study',
      'title': '我的书房',
      'icon': 'fa fa-deviantart',
      'path': '',
      'thumb': 'null',
      'type': 1,
      'hide': 0
    },
    {
      'id': 199,
      'pid': 0,
      'top': 0,
      'home': 0,
      'name': 'healthy',
      'title': '健康管理',
      'icon': 'fa fa-comments',
      'path': '',
      'thumb': 'null',
      'type': 1,
      'hide': 0
    },
    {
      'id': 201,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'gift',
      'title': '生日礼品券',
      'icon': '',
      'path': 'index.php?c=home&a=first&do=gift',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 202,
          'pid': 201,
          'top': 0,
          'home': 0,
          'name': 'gift',
          'title': '生日礼品券',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 203,
              'pid': 202,
              'top': 0,
              'home': 0,
              'name': 'gift_list',
              'title': '礼品券配置',
              'icon': '',
              'path': 'index.php?c=gift&a=list',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 204,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'chairman',
      'title': '工会主席信箱',
      'icon': 'fa fa-comments',
      'path': 'index.php?c=home&a=first&do=chairman',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 205,
          'pid': 204,
          'top': 0,
          'home': 0,
          'name': 'chairman',
          'title': '工会主席信箱',
          'icon': '',
          'path': '',
          'thumb': 'null',
          'type': 1,
          'hide': 0,
          'children': [
            {
              'id': 206,
              'pid': 205,
              'top': 0,
              'home': 0,
              'name': 'chairman_lists',
              'title': '收件箱',
              'icon': 'wxgh icon-walk-set',
              'path': 'index.php?c=chairman&a=index',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 207,
              'pid': 205,
              'top': 0,
              'home': 0,
              'name': 'chairman_pubilshed',
              'title': '已发送',
              'icon': 'wxgh icon-pat-info',
              'path': 'index.php?c=chairman&a=published',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 209,
              'pid': 205,
              'top': 0,
              'home': 0,
              'name': 'chairman_add',
              'title': '工会主席列表',
              'icon': 'wxgh icon-walk-set',
              'path': 'index.php?c=chairman&a=chairman',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 210,
              'pid': 205,
              'top': 0,
              'home': 0,
              'name': 'chairman_question',
              'title': '常见问题',
              'icon': 'wxgh icon-canteen-result',
              'path': 'index.php?c=chairman&a=question',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            },
            {
              'id': 211,
              'pid': 205,
              'top': 0,
              'home': 0,
              'name': 'chairman_setting',
              'title': '设置',
              'icon': 'wxgh icon-canteen-result',
              'path': 'index.php?c=chairman&a=setting',
              'thumb': 'null',
              'type': 1,
              'hide': 0
            }
          ]
        }
      ]
    },
    {
      'id': 212,
      'pid': 0,
      'top': 0,
      'home': 0,
      'name': 'actscene',
      'title': '活动现场管理',
      'icon': '',
      'path': '',
      'thumb': 'null',
      'type': 1,
      'hide': 0
    },
    {
      'id': 213,
      'pid': 0,
      'top': 0,
      'home': 0,
      'name': 'detection',
      'title': '工会巡检',
      'icon': '',
      'path': '',
      'thumb': 'null',
      'type': 1,
      'hide': 0
    },
    {
      'id': 67,
      'pid': 0,
      'top': 0,
      'home': 1,
      'name': 'memberManage',
      'title': '会员管理模块',
      'icon': 'form',
      'path': 'index.php?c=home&a=first&do=canteen',
      'thumb': 'null',
      'type': 1,
      'hide': 0,
      'children': [
        {
          'id': 344,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'dictionaryManage',
          'title': '字典管理',
          'icon': 'form',
          'path': '\/a\/#\/role\/dictionaryManage',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 345,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'roleManage',
          'title': '角色管理',
          'icon': 'form',
          'path': '\/a\/#\/role\/roleManage',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 346,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'roleCreate',
          'title': '新增角色',
          'icon': 'form',
          'path': '\/a\/#\/role\/roleCreate',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 347,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'roleDetail',
          'title': '角色详情',
          'icon': 'form',
          'path': '\/a\/#\/role\/roleDetail',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 348,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'roleEditBasic',
          'title': '角色基本信息修改',
          'icon': 'form',
          'path': '\/a\/#\/role\/roleEditBasic',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 349,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'roleEditAuthority',
          'title': '模块权限',
          'icon': 'form',
          'path': '\/a\/#\/role\/roleEditAuthority',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 350,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'roleEditUser',
          'title': '角色用户',
          'icon': 'form',
          'path': '\/a\/#\/role\/roleEditUser',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 351,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'accountManage',
          'title': '账户管理',
          'icon': 'form',
          'path': '\/a\/#\/role\/accountManage',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 352,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'accountDetail',
          'title': '账户详情',
          'icon': 'form',
          'path': '\/a\/#\/role\/accountDetail',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 353,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'AccountEdit',
          'title': '修改账户',
          'icon': 'form',
          'path': '\/a\/#\/role\/accountEdit',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 354,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'accountCreate',
          'title': '新增账户',
          'icon': 'form',
          'path': '\/a\/#\/role\/accountCreate',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        },
        {
          'id': 355,
          'pid': 67,
          'top': 0,
          'home': 0,
          'name': 'openFunction',
          'title': '开放功能',
          'icon': 'form',
          'path': '\/a\/#\/role\/openFunction',
          'thumb': 'null',
          'type': 1,
          'hide': 0
        }
      ]
    }
  ],
  'msg': '请求成功'
}
